### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by BenTangora** [Benjie-E/classic-games#107]
Git issue for the final presentation. Figured we would need this at some point so might as well make it now.

**Comment by JohnnyG1234** [comment]
https://docs.google.com/presentation/d/14gvKVVJrjMN4jVwjxcTIYPM7T9WIDrfekDBpleRTEBs/edit?usp=sharing
Made a slideshow for it

**Comment by JohnnyG1234** [comment]
Made a basic outline for the slideshow, its very rough but should help us in the future
