### ISSUE TITLE
Minesweeper win condition

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#108]
The game needs to check if all the empty squares have been revealed in order to determine when the player has won. There are definitely several ways to do this, but the first thing that comes to mind for me is to have a counter for every time the player reveals a square and have them win once that counter reaches (total squares minus squares w/ mines). That way, we don't have to check the entire board every 2 seconds.

**Comment by BenTangora** [comment]
Yeah. We should also throw something in there for if a mine is revealed just for ease of use. Something that might be messy would be having a function that returns either 1 (keep playing), 2 (player victory) or 3 (player defeat) for the condition of the board.

**Comment by BenTangora** [comment]
I wrote the basic implementation of a function to do this called checkGameState in the GameManager.

**Comment by nfischer623** [comment]
Would be nice if we changed the win condition to the way the real Minesweeper works, which is when the player has revealed all of the squares that do not have mines. It would basically just be the inverse of the way we have it now (instead of placing all the flags, which is a lot less risky and therefore less fun(?) than opening up squares). Going to make a new issue.
