### ISSUE TITLE
Read access violation (Minesweeper)

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#118]
When replaying the game, a Read Access Violation exception is thrown from the GameManager destructor.

(Just creating this issue so it has a history of documentation - I just solved it. Commit coming up pronto.)

**Comment by BenTangora** [comment]
Sweet. What was causing it?

**Comment by nfischer623** [comment]
https://github.com/Benjie-E/classic-games/commit/2a798fdf8a4466a6cb1d44d581533d65b30f8c36
