### ISSUE TITLE
Minesweeper - Squares revealed win condition

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#137]
See my comment here:
https://github.com/Benjie-E/classic-games/issues/108#issuecomment-1517245732

**Comment by BenTangora** [comment]
Got rid of the ability to win by having everything flagged and made a new function called updateRevealed that runs when someone has selected to reveal a square. Similar to how the flag victory was calculated, I have it increase a number until it reaches the desired goal (total squares - number of mines).

**Comment by nfischer623** [comment]
I was able to win on Easy. All set.
