### ISSUE TITLE
Minesweeper first move

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#138]
Currently, the first move is a complete gamble. I remember we talked about placing the mines AFTER the player picks their first move, which might be a little rough to code at this point...maybe we could just have a function that picks a safe first move? This is definitely a low priority thing, as the game certainly isn't unplayable in its current state.

**Comment by BenTangora** [comment]
I'm going to write a small function that pics a random non mined square and reveals it as the first move. While it may remove player agency no one wants to blow up on their first pick.

**Comment by nfischer623** [comment]
Made some changes (see https://github.com/Benjie-E/classic-games/commit/82d8c689f175a6eeca19efd0e0128fc2b9e986df), but this should be all taken care of.
