### ISSUE TITLE
Minesweeper chaining

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#139]
This is entirely quality of life (except for the fact that it could make the player's first moves a lot less luck-based). We would need a function very similar to the one that counts for adjacent mines that checks for other 0-count squares every time the player reveals a 0-count square and just recursively reveals 0-count squares. It sounds complicated, but I don't actually think it would be that bad, besides the potential for weird bugs.

**Comment by BenTangora** [comment]
Should this check all the squares or just up, down, left and right?

**Comment by nfischer623** [comment]
Just up down left right

**Comment by nfischer623** [comment]
I believe this is all set, barring any future needed bugfixes.
