### ISSUE TITLE
figure out c-make

### ISSUE THREAD

**Issue by JohnnyG1234** [Benjie-E/classic-games#24]

**Comment by BenTangora** [comment]
I found this helpful guide hhttps://cliutils.gitlab.io/modern-cmake/. It has some helpful information in general but also about how projects should be set up as well.

**Comment by JohnnyG1234** [comment]
Started work on Cmake but I'm having trouble getting it to work with PDcurses, I thinking about getting help from Scott Barret (The Goat)

**Comment by JohnnyG1234** [comment]
So I ended up trying to get the original source files for the code instead of the files that were in the new sln for the menu screen so my original cmake branch is pretty scuffed and I think I'm going to scrape it for parts basially and rename it to salvage cmake or something. Then I'll make a new branch and go from there with the intention of it being merged back into main at some point.

**Comment by JohnnyG1234** [comment]
So I made a new branch and worked fixed a lot of the problems but its still having trouble finding curses.h so I need to put a little more work in, ITS CLOSE I CAN FEEL IT

**Comment by BenTangora** [comment]
Thank you so much for doing this and trouble shooting it.

**Comment by JohnnyG1234** [comment]
GOOD NEWS I got the cmake to work in visual studio thanks to the goat CHIRS DEGUISE. The next step is getting it to run on a mac and we will see how that goes...

**Comment by JohnnyG1234** [comment]
going to close this issue and make a new one for using cmake on a mac
