### ISSUE TITLE
Playtest Connect 4

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#35]
All team members should playtest each other's games at some point.

**Comment by BenTangora** [comment]
Looks good and plays really nicely (I love moving the cursor). The art and spacing also looks great. However I tied to game and it didn't stop/register. It's very hard but here is how it looks when a game of connect 4 ends in a tie https://www.youtube.com/watch?v=dxbA5IhVaSQ. Also idk how we are going to do game looping in the end but you may want to add a way to do that as well.

**Comment by nfischer623** [comment]
I'm going to be adding the ability to draw and replay this weekend - have been slammed with work from other classes all week, so I unfortunately haven't gotten around to it yet. It will be there by Monday's class, though.

> Looks good and plays really nicely (I love moving the cursor). The art and spacing also looks great. However I tied to game and it didn't stop/register. It's very hard but here is how it looks when a game of connect 4 ends in a tie https://www.youtube.com/watch?v=dxbA5IhVaSQ. Also idk how we are going to do game looping in the end but you may want to add a way to do that as well.

**Comment by BenTangora** [comment]
> 

no problem or pressure I totally get it.

**Comment by BenTangora** [comment]
Ok I tested it and the draw/tie works!

**Comment by JohnnyG1234** [comment]
Looks good, I love how you can use the arrow keys to move the cursor

**Comment by Benjie-E** [comment]
add down to press
