### ISSUE TITLE
Playtest Hangman

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#36]
All team members should playtest each other's games at some point.

**Comment by BenTangora** [comment]
I really liked the art and how the words/letters appeared. I would maybe add some text feedback for the user and switch around where the word to be guessed and where the letters that have been guessed are. Also the menu is awesome!

**Comment by nfischer623** [comment]
At first I tried just opening Hangman.sln, but it couldn't find the words file for some reason, so I had to open it through classicgames.sln. I agree, the menu is a great start. The ascii art for Hangman also looks great.

A few things I think might be a good idea to add before we move to phase 2:
- Give a little more user feedback (e.g. "You Lost!" when the player loses, instead of just quitting the game immediately)
- After you win the game, provide a way to either play again or quit
- Also, after the player wins, you should stop accepting their input for letters (I could still "lose" after I won, if that makes sense. It was also the only way I could exit the game after winning without hitting stop on the debugger)

Again, I super appreciate you making the menu. Hopefully we'll all be ready to add our games into it by tomorrow and all of the Git stuff will go...semi-smoothly.

**Comment by JohnnyG1234** [comment]
Wow that main menu looks awesome and the arrow key for choosing what game to play works really well. I think just a little more work on the end states of hangman and it will be perfect
