### ISSUE TITLE
Playtest Wordle

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#38]
All team members should playtest each other's games at some point.

**Comment by BenTangora** [comment]
I am very bad at it but it runs and looks good. I noticed a couple of grammar/printing errors on the welcome screen and when it asked if the player would like to play again. Also I don't know if wordle does this but it might be cool to have the welcome screen/instructions up, since right now they disappear after the first go around. Not really an issue at all though.

**Comment by nfischer623** [comment]
Like Ben said, it looks good. The colors are an essential part of Wordle so they are very well used here. I also took a look at that words file, and wow, there are a lot of words (which is good).

A few suggestions before we move to phase 2:
- Like Ben said, there are some grammar errors (inconsistent punctuation/capitalization, missing words, etc.). Let me know if you want me to look it over to help you edit.
- In the actual NYT Wordle, you get 6 tries to guess the word, not 5. If you just want it to be an extra hard version of Wordle, feel free to keep the 5 guesses. Just wanted to make sure you knew.
- In the replay menu, pressing any key other than Y terminates the program. You should limit it to just being N, since that's what you're telling the user to press. (either that, or tell the user to press Y to play again, any other key to quit)
- When the game ends, the printed message cuts off the last "---------" line of the UI. This would just be a matter of adding a mvprintw() or move() function to move the cursor down a line or two so you don't overwrite anything.
- Like I suggested with Tic Tac Toe, I recommend hiding the cursor with curs_set(0).

This might be a big feature to add so late, so I'm putting it down here at the end, but it would be nice to be able to hit backspace and retype letters/press ENTER when I'm ready to submit my guess. The NYT Wordle also only allows you to submit valid English words as guesses (this would probably be the simplest part, as it would just be a matter of searching through the words file). Again, there probably isn't enough time for this, but just something to consider if you ever want to come back to this phase of the project later on.

**Comment by JohnnyG1234** [comment]
fixed most of these issue, and I think I might go back to add the feature where it only takes in actual words later. Though it does not seem to be that hard to do honestly.

**Comment by Benjie-E** [comment]
lets non letter buttons such as numbers and backspace fill up spaces. Should be able to backspace if word not finished to edit it.
