### ISSUE TITLE
Playtest TTT

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#39]
All team members should playtest each other's games at some point.

**Comment by nfischer623** [comment]
The gameboard is very nice and clean-looking. I also like the use of colors - it adds some nice visual distinction between the two players. I also appreciate the replay menu.

A few improvements that I could think of:
- Invalid moves: A very small thing, but currently, it says "Invald move." Just a typo fix. You could actually get rid of "invalid moves" in general; you can just do a switch statement in a while(true) loop with getchar() that ONLY specifies the 10 number keys. Feel free to take a look at GameManager.cpp in the Connect 4 files if you want a reference (I only take the arrow keys, ENTER, and SPACEBAR as inputs; everything else just falls into an empty default case).
- I would actually recommend hiding the cursor with curs_set(0), as there aren't really any points where the cursor being on-screen provides visual clarity. That's up to you, though.

Something else I noticed, but I'm putting it down here because I think it will get fixed when we start moving into CMake territory - when I tried to compile on my machine using VS 2019, I had to change the build tools for the project from v143 (VS 2022 tools) to v142.

**Comment by BenTangora** [comment]
Thanks! I didn't know about the cursor thing. I also had to change the build tools for everyone using the 2019 version of VS.

**Comment by JohnnyG1234** [comment]
Looks good, very simple and clear ui, my only idea would be to add some more text telling how to play the game but this does not seem to be that big of an issue

**Comment by BenTangora** [comment]
playtest completed and game merged with main.
