### ISSUE TITLE
Next Game Setup

### ISSUE THREAD

**Issue by BenTangora** [Benjie-E/classic-games#40]
- Create the folders to hold the new games
- Create the branches in git for the new games
- Create and configure the new games VS files

**Comment by nfischer623** [comment]
Teams are:

1. Nicole and Ben
2. John and Benjie

Games TBA.

**Comment by nfischer623** [comment]
Games:

1. Nicole and Ben: Minesweeper
2. John and Benjie: Snake

**Comment by nfischer623** [comment]
I believe both projects are set up, so I'm going to close this issue.
