### ISSUE TITLE
Minesweeper Board Printer

### ISSUE THREAD

**Issue by BenTangora** [Benjie-E/classic-games#67]
Function to display a basic minesweeper board. First implementation will probably be just getting the board to print correctly.

**Comment by BenTangora** [comment]
Depending on how we want to make the cursor/interaction method we could try and highlight the sides of the selected square in another color. I have no clue if we can actually do that though.

**Comment by nfischer623** [comment]
@BenTangora do you think you can have this ready to go by Monday? I can help you with it this weekend if you think you need a second set of eyes.

**Comment by BenTangora** [comment]
Now displays the board, the maximum amount of flags, and the amount of flags currently placed. Also displays the difficulty and I left some space to show basic controls.

**Comment by nfischer623** [comment]
@BenTangora Just tried running this - the board doesn't quite display correctly on my screen. Maybe it has something to do with my aspect ratio? I noticed when I was making Connect 4 that resizing the window completely broke the formatting, and the same thing happens here. We'll take a look at this later tonight.

**Comment by BenTangora** [comment]
Yeah you need to change up the window size, since the default is to small. I haven't looked into how to make it so that the program itself controls the console size. But you can right click the console window and change some settings around there. I set a width of 100 and a height of 40 on my machine which gives me more than enough space.

**Comment by nfischer623** [comment]
Okay, that works for me for the time being. From some quick Googling, it looks like there are commands to resize the terminal, but things might get complicated.

I'm going to do a quick edit to add another space or two between squares on the same line so things line up a bit better.

**Comment by BenTangora** [comment]
Function has been implemented.
