### ISSUE TITLE
Review Connect 4 in the combined project

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#69]
There are a couple of things in Connect 4 that broke when we merged all the games together, so I need to look into fixing that. @Benjie-E , is it still just the wraparound glitch or are there more problems?

**Comment by Benjie-E** [comment]
It is that and when you leave the game and go back to the menu the enter key doesn't work to start another game.

**Comment by Benjie-E** [comment]
Fixed those issues
