### ISSUE TITLE
Conform to Visual Studio 2022

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#70]
It is with a heavy heart that I must announce we ALL need to be working in VS2022, not VS2019. If any of your files are using the 2019 build tools, please open them with VS2022 and reconfigure them with the 2022 build tools.

I accept any and all "LITERALLY 1984!" accusations.

**Comment by BenTangora** [comment]
Imagine not already using VS2022.

**Comment by nfischer623** [comment]
I think we're all up to date on this by now.
