### ISSUE TITLE
Minesweeper Endgame screen

### ISSUE THREAD

**Issue by BenTangora** [Benjie-E/classic-games#91]
We need an end game screen or screen layout at the very least. One for Victory and one for blowing yourself up (in game). This should give the player their final score and maybe reveal the entire map.

**Comment by BenTangora** [comment]
Should we have it so the board is still displayed so the player can see where all of the mines were or should we just draw a new screen and not show the board?

**Comment by nfischer623** [comment]
Revealing the board would probably modifying the stats function, but it would be more like the actual Minesweeper. Best way to do that is probably just to pass the win state to displayStats() and have an if statement that either prints the stats OR the win/lose message, and make sure that takes up the same amount of space that the stats would.

**Comment by BenTangora** [comment]
oh yeah that's a good idea. Does the formation of (Victory Condition - Difficulty - Mines) look good to you?

**Comment by nfischer623** [comment]
What do you mean? Like replacing the "Minesweeper" text with "YOU WIN" (or something) and then keeping the stats box?

**Comment by BenTangora** [comment]
no replacing the stats box info with the text. I made a rough version of it in the branch if you want to take a look.

**Comment by nfischer623** [comment]
I just looked at it, I think a phrase like "Lose on Easy" is a little unclear. Maybe just keep the stats box and change "Minesweeper" to a win/lose message. It conveys all the same information, just a little more clearly IMO.

**Comment by BenTangora** [comment]
alrighty!

**Comment by BenTangora** [comment]
And for the message how does "You lost on Easy" and "You won on Easy" sound to you?

**Comment by nfischer623** [comment]
I personally don't think it's necessary to have the difficulty in the win/lose message since it's already in the stats box, but do whatever looks best to you.

**Comment by BenTangora** [comment]
Oh yeah lol

**Comment by BenTangora** [comment]
Ok the title might be slightly off since I rounded down but take a look and tell me what you think.

**Comment by nfischer623** [comment]
Looking good. Could do with maybe an exclamation point (they WON MINESWEEPER! good for them)
