### ISSUE TITLE
Minesweeper keyboard input

### ISSUE THREAD

**Issue by nfischer623** [Benjie-E/classic-games#94]
We need to make it so that the player can move the cursor and reveal/flag squares. I think we already determined the control scheme? I'd have to review the whiteboard sketches.

On the same note, we need to figure out how we want to visually distinguish which square is currently being "selected" by the player. Another thing to consider is if we want the cursor to skip over squares that have already been revealed, or if we just want the reveal/flag buttons to do nothing on revealed squares. The former is more intuitive, but the latter is simpler to code.

**Comment by nfischer623** [comment]
> On the same note, we need to figure out how we want to visually distinguish which square is currently being "selected" by the player. Another thing to consider is if we want the cursor to skip over squares that have already been revealed, or if we just want the reveal/flag buttons to do nothing on revealed squares. The former is more intuitive, but the latter is simpler to code.

@BenTangora what do you think about this?

**Comment by BenTangora** [comment]
Totally forgot about this. We could change the background color of the square they are selecting or maybe draw a box around the square. As for how we want the selector to move I would say we should get it working and then make it skip over revealed tiles if we want to.

**Comment by nfischer623** [comment]
Is there a way to draw boxes around things? That would probably be ideal, since picking a different background color could get kind of wonky, especially if we want the cursor to be able to highlight squares that have already been revealed (I exhausted all of the terminal colors on the different numbers).

**Comment by BenTangora** [comment]
It would be tricky but we could use the line draw functions like I think hline to draw it. Although I haven't looked into it to much. We could also try something like connect 4 if we need to, but I think that will get way hard to see which square the player has selected on the larger boards.

**Comment by nfischer623** [comment]
Alright. I think the solution here might be to highlight with a different color and just make the cursor skip over revealed squares. I don't think it would be too insane to code.

**Comment by BenTangora** [comment]
sweet

**Comment by nfischer623** [comment]
https://github.com/Benjie-E/classic-games/commit/97ba78e2791e593bb3e593df69c9ffe51880dcb4
Progress has been made.
